// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"authentication.mdx": () => import("../content/docs/authentication.mdx?collection=docs"), "hola-mundo-claude-mcp.mdx": () => import("../content/docs/hola-mundo-claude-mcp.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "quickstart.mdx": () => import("../content/docs/quickstart.mdx?collection=docs"), "roadmap.mdx": () => import("../content/docs/roadmap.mdx?collection=docs"), "api-reference/health.mdx": () => import("../content/docs/api-reference/health.mdx?collection=docs"), "concepts/conversations.mdx": () => import("../content/docs/concepts/conversations.mdx?collection=docs"), "concepts/invitations.mdx": () => import("../content/docs/concepts/invitations.mdx?collection=docs"), "concepts/messages.mdx": () => import("../content/docs/concepts/messages.mdx?collection=docs"), "concepts/queries.mdx": () => import("../content/docs/concepts/queries.mdx?collection=docs"), "sdks/python.mdx": () => import("../content/docs/sdks/python.mdx?collection=docs"), "sdks/typescript.mdx": () => import("../content/docs/sdks/typescript.mdx?collection=docs"), "realtime/webhooks.mdx": () => import("../content/docs/realtime/webhooks.mdx?collection=docs"), "realtime/websocket.mdx": () => import("../content/docs/realtime/websocket.mdx?collection=docs"), "api-reference/human/auth.mdx": () => import("../content/docs/api-reference/human/auth.mdx?collection=docs"), "api-reference/human/conversations.mdx": () => import("../content/docs/api-reference/human/conversations.mdx?collection=docs"), "api-reference/human/invitations.mdx": () => import("../content/docs/api-reference/human/invitations.mdx?collection=docs"), "api-reference/human/messages.mdx": () => import("../content/docs/api-reference/human/messages.mdx?collection=docs"), "api-reference/human/profile.mdx": () => import("../content/docs/api-reference/human/profile.mdx?collection=docs"), "api-reference/agent/conversations.mdx": () => import("../content/docs/api-reference/agent/conversations.mdx?collection=docs"), "api-reference/agent/invitations.mdx": () => import("../content/docs/api-reference/agent/invitations.mdx?collection=docs"), "api-reference/agent/key-rotate.mdx": () => import("../content/docs/api-reference/agent/key-rotate.mdx?collection=docs"), "api-reference/agent/messages.mdx": () => import("../content/docs/api-reference/agent/messages.mdx?collection=docs"), "api-reference/agent/profile.mdx": () => import("../content/docs/api-reference/agent/profile.mdx?collection=docs"), "api-reference/agent/queries.mdx": () => import("../content/docs/api-reference/agent/queries.mdx?collection=docs"), "api-reference/agent/register.mdx": () => import("../content/docs/api-reference/agent/register.mdx?collection=docs"), "api-reference/agent/upload.mdx": () => import("../content/docs/api-reference/agent/upload.mdx?collection=docs"), "api-reference/agent/webhooks.mdx": () => import("../content/docs/api-reference/agent/webhooks.mdx?collection=docs"), }),
};
export default browserCollections;